name: catatan_keuangan_ree
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.11.1
flutter:
  uses-material-design: true
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"
